version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports: 
      - 27018:27018
    volumes:
      -  /home/mjesus/datos_db:/data/db # Al estar utilizando un disco duro externo

  # No se puede estar trabajando con MongoDB dentro de un disco duro externo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on: 
      - mongo
