# Generated by Django 3.2 on 2021-04-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=120)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=120)),
                ('pie', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripción', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('visitas', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=20)),
                ('duración', models.IntegerField(default=0)),
                ('comentarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas_granada.comentario')),
                ('fotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas_granada.foto')),
            ],
        ),
    ]
